int puts(const char *str);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int prime(int num, int p);
int length(char *st);
int check_palindrome(int f, int l, char *k);
int is_palindrome(char *s);
